name: test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
            path: ~/.konan
            key: "${{ runner.os }}-${{ hashFiles('**/.lock') }}"

      - name: Setup Java
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
        with:
          gradle-version: current

      - uses: burrunan/gradle-cache-action@c15634bb25b7284dc084f38dff4e838048b7feaf # v2
        name: Build
        with:
          gradle-version: current
          gradle-build-scan-report: false
          read-only: ${{ github.ref != 'refs/heads/main' }}
          job-id: jdk21
          arguments: build

      - name: Collect Tests Result
        if: ${{ failure() }}
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08
        with:
          name: tests-result
          path: ${{ github.workspace }}/**/build/reports/tests
